### ISSUE TITLE
settings-button size

### ISSUE THREAD

**Issue by Rex2002** [Rex2002/sound-shapes#19]
currently the buttons that open the settings pane are very hard to click. 
Probably easily fixable by changing the background of the icons to non-transparent, but I fear my gimp-skills are not powerful enough for this

**Comment by MalteRichert** [comment]
@Rex2002 do you still experience this on current main? I changed the settings to be opened onAction for the entire tab surrounding the icon which should have fixed this.

However, I am still annoyed with this for the volume button. I will just layer an invisible square over that to fix this
